repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v1.25.3
  hooks:
    - id: pyupgrade
      args: [--py36-plus]
- repo: https://github.com/4Catalyzer/fourmat
  rev: master
  hooks:
    - id: fourmat
- repo: https://github.com/asottile/blacken-docs
  rev: v1.4.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.10b0]
