repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
    - id: pyupgrade
      args: [--py310-plus]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.3
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/asottile/blacken-docs
  rev: 1.16.0
  hooks:
    - id: blacken-docs
      additional_dependencies: [black==23.12.1]
