repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
    - id: pyupgrade
      args: [--py39-plus]
- repo: https://github.com/4Catalyzer/fourmat
  rev: v0.11.1
  hooks:
    - id: fourmat
      additional_dependencies: [setuptools>69]
- repo: https://github.com/asottile/blacken-docs
  rev: 1.16.0
  hooks:
    - id: blacken-docs
      additional_dependencies: [black==23.12.1]
