repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v1.18.0
  hooks:
    - id: pyupgrade
- repo: https://github.com/4Catalyzer/fourmat
  rev: master
  hooks:
    - id: fourmat
- repo: https://github.com/asottile/blacken-docs
  rev: v1.0.0-1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==19.3b0]
