repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.0
  hooks:
    - id: pyupgrade
      args: [--py37-plus]
- repo: https://github.com/4Catalyzer/fourmat
  rev: v0.10.1
  hooks:
    - id: fourmat
- repo: https://github.com/asottile/blacken-docs
  rev: v1.11.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==20.8b1]
