language: python
sudo: false
python:
  - "2.7"

before_install:
  - pip install -U pip
install:
  - pip install -Ue .[jwt]
  - pip install -U coveralls flake8 mock pytest pytest-cov

script:
  - python setup.py test

after_success:
  - coveralls

branches:
  only:
    - master
