dist: xenial

language: python

jobs:
  include:
    - { python: "3.8", env: "TOXENV=lint" }

    - { python: "3.7", env: "TOXENV=py-full DATABASE_URL=postgres://localhost/travis_ci_test" }
    - { python: "3.8", env: "TOXENV=py-full DATABASE_URL=postgres://localhost/travis_ci_test" }

    - { python: "3.6", env: "TOXENV=py-base" }
    - { python: "3.7", env: "TOXENV=py-base" }
    - { python: "3.8", env: "TOXENV=py-base" }

    - { python: "3.8", env: "TOXENV=docs" }

    - stage: PyPI Release
      if: tag IS present
      python: "3.8"
      env: []
      before_install: skip
      install: skip
      before_script: skip
      script: skip
      after_success: skip
      deploy:
        provider: pypi
        user: "__token__"
        password:
          secure: "pypi-AgEIcHlwaS5vcmcCJGFkMmQ4MWVjLThmY2MtNGU1ZC04YTdiLTkxODQxNjMwMmJiYgACPHsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJmbGFzay1yZXN0eSJdfSwgInZlcnNpb24iOiAxfQAABiBcT6Q3J-IZXm_H2PAV71RZb4VnHePtOV7OvA0jLQrlIw"
        on:
          tags: true
        distributions: sdist bdist_wheel

services:
  - postgresql


cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - pip install -U pip
install:
  - pip install -U codecov tox

before_script:
  - psql -c 'CREATE DATABASE travis_ci_test' -U postgres
script:
  - tox

after_success:
  - codecov

branches:
  only:
    - master
