language: python
sudo: false
python:
  - "2.7"

before_install:
  - pip install -U pip
install:
  - pip install -Ue .
  - pip install -U flake8 pytest pytest-cov coveralls

script:
  - flake8 .
  - py.test --cov=flask_jsonapiview

after_success:
  - coveralls

branches:
  only:
    - master
