language: python
dist: xenial
services:
  - postgresql
jobs:
  include:
    - { python: "3.7",   env: "TOXENV=lint" }
    - { python: "3.6",   env: "TOXENV=py-full-marshmallow2 DATABASE_URL=postgres://localhost/travis_ci_test" }
    - { python: "3.7",   env: "TOXENV=py-full-marshmallow2 DATABASE_URL=postgres://localhost/travis_ci_test" }

    - { python: "3.6",   env: "TOXENV=py-base-marshmallow2" }

    - { python: "3.6",   env: "TOXENV=py-full-marshmallow3" }
    - { python: "3.6",   env: "TOXENV=py-base-marshmallow3" }

    - { python: "3.7",   env: "TOXENV=docs" }

    - stage: PyPI Release
      if: tag IS present
      python: "3.7"
      env: []
      before_install: skip
      install: skip
      before_script: skip
      script: skip
      after_success: skip
      deploy:
        provider: pypi
        user: taion
        on:
          tags: true
        distributions: sdist bdist_wheel
        password:
          secure: "CHANGEME"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - pip install -U pip
install:
  - pip install -U codecov tox

before_script:
  - psql -c 'CREATE DATABASE travis_ci_test' -U postgres
script:
  - python setup.py test

after_success:
  - codecov

branches:
  only:
    - master
